version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - payment-processor
      - backend
    depends_on:
      - payments1
      - payments2
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "40MB"
  payments1:
    build: .
    container_name: payments1
    networks:
      - payment-processor
      - backend
    ports:
      - "8081"
    volumes:
      - payments_data:/data
    tmpfs:
     - /tmpfs
    environment:
      - WORKER_COUNT=14
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "155MB"

  payments2:
    build: .
    container_name: payments2
    networks:
      - payment-processor
      - backend
    ports:
      - "8081"
    volumes:
      - payments_data:/data
    tmpfs:
     - /tmpfs
    environment:
      - WORKER_COUNT=14
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "155MB"

volumes:
  payments_data:
    driver: local

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true